apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-service-config
  labels:
    app: alert-service
data:
  ALERT_SERVICE_DATABASE_URI: postgresql+psycopg2://weather:weather@postgres:5432/alert_service
  REDIS_URL: redis://redis:6379/1
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  RABBITMQ_EXCHANGE: weather_alerts
  RABBITMQ_ROUTING_KEY: alert.notification
  NOAA_USER_AGENT: WeatherAlerts/1.0 (ops@example.com)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: ghcr.io/example/alert-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: alert-service-config
          readinessProbe:
            httpGet:
              path: /docs
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
spec:
  selector:
    app: alert-service
  ports:
    - port: 8002
      targetPort: 8002
