openapi: 3.0.3
info:
  title: Alert Service API
  version: 0.1.0
servers:
  - url: https://api.example.com/alert-service
paths:
  /api/v1/alerts:
    get:
      summary: List recent alerts
      responses:
        '200':
          description: Alert list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alert'
  /api/v1/subscriptions:
    post:
      summary: Create alert subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionCreate'
      responses:
        '201':
          description: Created subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
  /api/v1/alerts/{alertId}/dispatch:
    post:
      summary: Trigger notification dispatch for alert
      parameters:
        - in: path
          name: alertId
          schema:
            type: integer
          required: true
      responses:
        '202':
          description: Dispatch accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: integer
components:
  schemas:
    Alert:
      type: object
      properties:
        id:
          type: integer
        external_id:
          type: string
        title:
          type: string
        description:
          type: string
        severity:
          type: string
        event:
          type: string
        sent:
          type: string
          format: date-time
        geometry:
          type: object
    SubscriptionCreate:
      type: object
      required: [user_id, alert_types, area_geojson]
      properties:
        user_id:
          type: string
        alert_types:
          type: array
          items:
            type: string
        area_geojson:
          type: object
    Subscription:
      allOf:
        - $ref: '#/components/schemas/SubscriptionCreate'
        - type: object
          properties:
            id:
              type: integer
